### PR TITLE
This PR adds the different section of the website.

### PR DESCRIPTION
**Pull request by Koushith**
# Adds
- Header, icons, buttons, and overall website structure.
- Tablet Responsiveness

## Todo
- [ ] Mobile responsiveness, color scheme.
- [ ] Contents, making pixel perfect as per Figma design.

ezgif com-optimize

### CODE REVIEW

**Comment by abhinav-anshul** [comment]
We are rendering tech stack as an SVG image, Is the best way to do so? It would not be responsive. Consider rendering tech stack as custom CSS grid instead of an SVG image

**Comment by koshikraj** [comment]
This PR looks good to me with the basic layout as per the mockup. @Koushith will you be working on the TODOs mentioned in this PR?

**Comment by Koushith** [comment]
> We are rendering tech stack as an SVG image, Is the best way to do so? It would not be responsive. Consider rendering tech stack as custom CSS grid instead of an SVG image

sure.. replacing Techstack section with Grid now.

**Comment by Koushith** [comment]
> This PR looks good to me with the basic layout as per the mockup. @Koushith will you be working on the TODOs mentioned in this PR?

no, for the enhancement, I have made a separate Branch. will push that ASAP!!

**Comment by koshikraj** [comment]
> > This PR looks good to me with the basic layout as per the mockup. @Koushith will you be working on the TODOs mentioned in this PR?
> 
> no, for the enhancement, I have made a separate Branch. will push that ASAP!!

Okay, great! Is there any further update in this branch or can we merge this?

**Comment by Koushith** [comment]
> > > This PR looks good to me with the basic layout as per the mockup. @Koushith will you be working on the TODOs mentioned in this PR?
> > 
> > 
> > no, for the enhancement, I have made a separate Branch. will push that ASAP!!
> 
> Okay, great! Is there any further update in this branch or can we merge this?

we can merge this branch, anyhow I'm working on a separate branch (enhancements).

**Pull request merged**
